from domain.services.factories.core_dependency_injection_factory import CoreDependecyInjectionFactory
from domain.services.factories.database_controller_factory import DatabaseControllerFactory
from domain.services.factories.database_connection_factory import ConnectDatabaseFactory
from domain.services.factories.produto_factory import ProdutoFactory